# Generated by Django 5.0.2 on 2025-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('News', 'News'), ('Gadget', 'Gadget'), ('Programming', 'Programming')], default='Tech', max_length=20),
        ),
    ]
